### ISSUE TITLE
missing antialiasing in the overview

### ISSUE THREAD

**Issue by m0rphtail** [yilozt/mutter-rounded#1]
### Overview with mutter-rounded:
![image](https://user-images.githubusercontent.com/47940274/140533676-e538b2e3-3163-4a87-a092-b7f24c03be36.png)

### Overview with default mutter
![image](https://user-images.githubusercontent.com/47940274/140533478-3478624d-6de7-4cff-8688-92575f498ee5.png)

**Comment by yilozt** [comment]
I have added texture filters to `MetaClipEffect`. The antialiasing in overview should works now.
You can edit [line 51](https://github.com/yilozt/mutter-rounded/blob/main/aur/meta_clip_effect.c#L51) in `meta_clip_effect.c` to set suitable texture filters if you like. This [Cogl Document](https://developer-old.gnome.org/cogl-2.0-experimental/stable/cogl-2.0-experimental-Pipeline.html#cogl-pipeline-set-layer-filters) will help you if you want to edit this file.

**Comment by m0rphtail** [comment]
awesome, thanks :+1:
