### ISSUE TITLE
Update for gnome43

### ISSUE THREAD

**Issue by radical4ever** [yilozt/mutter-rounded#103]
Hi i really like more this one than the extension itself(it doesnt round all the corners), is it possible to upgrade it to gnome 43?, thank you

**Comment by yilozt** [comment]
Sorry that I will not maintain this patch in the future, an important reason is it might broken this patch when Mutter updated, then I have to apply patch again and fix conflict. As the time goes, I have to maintain _different_ version of patches, even they have _same_ features.

More and more patches with same features will be added, just for making it work on different gnome-shell versions. But when I want to fix an issues, I have to update those accumulated patches in same time. So, sorry that I give it up, and moving to gnome-shell extensions.

**Comment by radical4ever** [comment]
> Sorry that I will not maintain this patch in the future, an important reason is it might broken this patch when Mutter updated, then I have to apply patch again and fix conflict. As the time goes, I have to maintain _different_ version of patches, even they have _same_ features.
> 
> More and more patches with same features will be added, just for making it work on different gnome-shell versions. But when I want to fix an issues, I have to update those accumulated patches in same time. So, sorry that I give it up, and moving to gnome-shell extensions.

Oh... ok i understand, i know that patching mutter its complex ,kinda dangerous and time comsuming. i hope someone could get into this work. thanks for aswering!

**Comment by Spirrwell** [comment]
I went through and redid the patches for mutter 43 and 43.1 here: https://github.com/Spirrwell/mutter-rounded
I'm not certain 43.1 works, because for whatever reason Fedora 37 still pulls the mutter 43.0 source even though it ships 43.1. 

The 43.0 patch does work as far as I can tell, though it seems to crash gnome-shell if I run it with the Blur My Shell extension. So use it at your own risk I suppose.

![image](https://user-images.githubusercontent.com/8671884/201504811-5b6c4db7-4438-485a-92fb-b6f4350c5124.png)

**Comment by radical4ever** [comment]
> I went through and redid the patches for mutter 43 and 43.1 here: https://github.com/Spirrwell/mutter-rounded I'm not certain 43.1 works, because for whatever reason Fedora 37 still pulls the mutter 43.0 source even though it ships 43.1.
> 
> The 43.0 patch does work as far as I can tell, though it seems to crash gnome-shell if I run it with the Blur My Shell extension. So use it at your own risk I suppose.
> 
> ![image](https://user-images.githubusercontent.com/8671884/201504811-5b6c4db7-4438-485a-92fb-b6f4350c5124.png)

You're AWESOME!, it works just as with gnome 42 and i have no issues with blur my shell enabled

**Comment by radical4ever** [comment]
@Spirrwell i guess if you're doing the job of applying the patches i can close this issue for now. thank you again!

**Comment by radical4ever** [comment]
> > I went through and redid the patches for mutter 43 and 43.1 here: https://github.com/Spirrwell/mutter-rounded I'm not certain 43.1 works, because for whatever reason Fedora 37 still pulls the mutter 43.0 source even though it ships 43.1.
> > The 43.0 patch does work as far as I can tell, though it seems to crash gnome-shell if I run it with the Blur My Shell extension. So use it at your own risk I suppose.
> > ![image](https://user-images.githubusercontent.com/8671884/201504811-5b6c4db7-4438-485a-92fb-b6f4350c5124.png)
> 
> You're AWESOME!, it works just as with gnome 42 and i have no issues with blur my shell enabled

the only issue i have with blur my shell its just that the window of the apps on overview makes them blurry

**Comment by gnolooo** [comment]
> I went through and redid the patches for mutter 43 and 43.1...

I'm writing here because I've seen your patches before on your github fork but I'm just not able to install them in Arch Linux. I've tried to clone the outdated mutter-rounded repo and then change the old patches with the new one but for some reason the build does not finish properly. So, do you have any idea on how to patch and install mutter rounded in Arch Linux too?

**Comment by Spirrwell** [comment]
> > I went through and redid the patches for mutter 43 and 43.1...
> 
> I'm writing here because I've seen your patches before on your github fork but I'm just not able to install them in Arch Linux. I've tried to clone the outdated mutter-rounded repo and then change the old patches with the new one but for some reason the build does not finish properly. So, do you have any idea on how to patch and install mutter rounded in Arch Linux too?

Well, I've never made a package on the AUR, so I'm really not too certain how it all works. But it looks like to me that the PKGBUILD points to the 42.3 version of mutter.

```
_commit=1903356b45c6c884a0451580f32494ff1288656d  # tags/42.3^0
_mutter_src="$pkgname::git+https://gitlab.gnome.org/GNOME/mutter.git#commit=$_commit"
```
The commit hash `8329a3eb5f4960df919e0348bd445c40568d3d60` should be mutter 43.1 which is the latest my updated patches target. I don't know where the PKGBUILD gets the .patch files from, I would have to dig a bit deeper to really figure it out.

I went ahead and enabled Issues on my fork if you want to open an issue there so we don't bloat this closed issue. Post whatever errors you're getting, and I can try to look into it further.
