### ISSUE TITLE
Mutter rounded not working in ubuntu 22.10 version.

### ISSUE THREAD

**Issue by shyamadsul** [yilozt/mutter-rounded#105]

**Comment by sam0218-gif** [comment]
In my pc mutter rounded don't install. terminal show "dpkg: error: cannot access archive 'libmutter-8-0*.deb': File or directory does not exist"

**Comment by sam0218-gif** [comment]
and in ./pacakge.sh show
"Supported version: 22.04 21.10
Current version: 22.10
exit." and doesn't download anything

**Comment by shyamadsul** [comment]
Issue closed!
