### ISSUE TITLE
Fedora 38 support

### ISSUE THREAD

**Issue by xwr-ron** [yilozt/mutter-rounded#112]
Hi, I've been using `mutter rounded` for a few years now.

I decided to install Fedora, but noticed that there is no support for the 38th release
If you have free time, please do it

**Comment by lendradev** [comment]
Hi, according to #103 issue, this project isn't maintain anymore.
use https://github.com/yilozt/rounded-window-corners instead of mutter-rounded if you using GNOME 42+

**Comment by xwr-ron** [comment]
> ###
> **[lendradxx](/lendradxx) ** commented [May 27, 2023](#issuecomment-1565081311) •

Okay, thanks for answer
