### ISSUE TITLE
When mutter_rounded installs, crashes gnome.

### ISSUE THREAD

**Issue by EmeraldLoc** [yilozt/mutter-rounded#29]
Don't exactly know what caused this to happen, i was using mutter_rounded earlier today, and then i updated, and it crashed gnome, might be a update.

**Comment by eliasvaltteri** [comment]
Same issue here. No idea about the cause yet, will update in case I find anything out.

**Comment by EmeraldLoc** [comment]
its probably an update with gnome, if you look at the master branch, he updated mutter rounded 6 days go.

**Comment by yilozt** [comment]
What's your linux distribution?

**Comment by yilozt** [comment]
Updated via commit [f0cdc4fb](https://aur.archlinux.org/cgit/aur.git/commit/?h=mutter-rounded&id=f0cdc4fb6632c03a6898528fab5fe8da3513e0e5) in AUR.

**Comment by EmeraldLoc** [comment]
Arch, sorry for late reply

**Comment by EmeraldLoc** [comment]
I will try it today and see if it is fixed

**Comment by EmeraldLoc** [comment]
It seems to be fixed now, closing issue. Hopefully no one is having the issue now.
