### ISSUE TITLE
mutter-rounded broke manjaro

### ISSUE THREAD

**Issue by denielt** [yilozt/mutter-rounded#44]
Updated my system today and reboot, then a white screen appeared before login screen where it says "Oh no! Something gone wrong." When I removed mutter-rounded imediately got system working again

**Comment by ajfpay** [comment]
Yeah same problem, after update broken

**Comment by nemoitis** [comment]
Same here. Fixed replacing it with `mutter`. When I tried to reinstall, it says 
```
disconnected from pipewire
cannot make connection with the bus.
```

**Comment by denielt** [comment]
> **UPDATE** : Cleaned cache and installed successfully.

How did you cleaned cache?

**Comment by nemoitis** [comment]
> > **UPDATE** : Cleaned cache and installed successfully.
> 
> How did you cleaned cache?

I use Yay, so for me it is `rm -rf ~/.cache/yay/mutter-rounded`.
