### ISSUE TITLE
Unable to resume from suspension in Wayland

### ISSUE THREAD

**Issue by Microwave-WYB** [yilozt/mutter-rounded#46]
In the most recent manjaro with gnome 41, I'm unable to resume my gnome session after suspend under wayland. There's no problem when I reinstalled normal mutter, and there's no problem under xorg session.

**Comment by 500InternalError** [comment]
same problem here.
gnome-log says
`/mutter-rounded/src/backends/native/meta-onscreen-native.c:1046):meta_onscreen_native_swap_buffers_with_damage: runtime check failed: (onscreen_native->gbm.next_fb == NULL`

**Comment by RedCommand** [comment]
same problem here.

**Comment by 500InternalError** [comment]
I guess it's a bug from upstream. I noticed that someone reported the same issue in https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1441?commit_id=6b8d25eb6370a5040185ac83b44e32e3189e0533 , and this repo also applies that patch. So I guess removing the mr1441.patch from PKGBUILD might help

**Comment by Microwave-WYB** [comment]
> Confirmed working after removing mr1441.patch

Wow it actually worked! Thanks a lot.

**Comment by Krindog7337** [comment]
> Confirmed working after removing mr1441.patch

How to remove mr1441.patch from PKGBUILD? Can't install it when removing mr1441.patch file

**Comment by 500InternalError** [comment]
> > Confirmed working after removing mr1441.patch
> 
> How to remove mr1441.patch from PKGBUILD? Can't install it when removing mr1441.patch file

comment or remove this
`  patch -p1 < $srcdir/mr1441.patch`
