### ISSUE TITLE
The Blur Effect settings dont do anything

### ISSUE THREAD

**Issue by kshitijaucharmal** [yilozt/mutter-rounded#5]
I have the arch version of mutter-rounded, and the rounded corners work perfectly fine, but the blur settings (I'm using mutter_setting) are not working as far as I can tell, could you tell me how to use it or If there is any problem 
I'm using gnome 41.1 with manjaro.

(Also the blurred window **opacity** is misspelled as **opaciry**)

**Comment by yilozt** [comment]
In Gnome 41 with Xorg session, you need to run `xprop WM_CLASS|cut -d \" -f 2` in a terminal to pick a window, copy the result. Then open `mutter_setting`, click `Add` button in Blur List, paste it to  the  `new_item` textfield. But in wayland, `xprop` will not work properly.

**Comment by yilozt** [comment]
I have update the mutter_settings, you can try to upgrade mutter-rounded by AUR.

After upgrade, you may need to logout gnome-session.  After relogin into gnome_session, you can pick a window and add it into blur list directly in mutter_settings.  the blur effect will effect when you open the a new window.

https://user-images.githubusercontent.com/32430186/142765425-cf67dff5-1469-407e-b333-23c7b786a4d1.mp4
