### ISSUE TITLE
Gnome 42 EndeavourOS

### ISSUE THREAD

**Issue by momoRaza** [yilozt/mutter-rounded#57]
Has anyone got this working in Gnome 42? Is there a fix?

Thanks

**Comment by momoRaza** [comment]
Thanks!, it wasn't working a couple of days ago but I just tried it again and it's working flawlessly.

**Comment by Aleksanaa** [comment]
> Thanks!, it wasn't working a couple of days ago but I just tried it again and it's working flawlessly.

Please remember to close this issue :)
