### ISSUE TITLE
Getting a source.list error

### ISSUE THREAD

**Issue by shreyansh1827** [yilozt/mutter-rounded#59]
After running,
_git clone https://github.com/yilozt/mutter-rounded
cd ./mutter-rounded/ubuntu
./package.sh_
i am getting this error
**E: Malformed entry 57 in list file /etc/apt/sources.list (Component)
E: The list of sources could not be read.
[err: 100] sudo apt update**
PLEASE HELP

**Comment by yilozt** [comment]
Seems to `/etc/apt/sources.list` in your system has broken. 
You can paste the content of this file by `cat /etc/apt/sources.list` to find problem.

**Comment by shreyansh1827** [comment]
Getting the same issue after pasting it

**Comment by yilozt** [comment]
You can run `sudo cat -n /etc/apt/sources.list`, copy the output, paste it to here, to let me know what's problem with this file if you don't mind.

If your follow the README.md, Open `Software & Updates` and enable all checkbox, then click Close Button, 
`packages.sh` will build packages correctly.

**Comment by shreyansh1827** [comment]
Here is the output 
1	# deb cdrom:[Ubuntu 20.04.1 LTS _Focal Fossa_ - Release amd64 (20200731)]/ focal main restricted
     2	
     3	# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
     4	# newer versions of the distribution.
     5	deb http://archive.ubuntu.com/ubuntu jammy main restricted
     6	deb-src http://archive.ubuntu.com/ubuntu jammy restricted multiverse main universe #Added by software-properties
     7	deb-src http://in.archive.ubuntu.com/ubuntu/ focal main restricted
     8	
     9	## Major bug fix updates produced after the final release of the
    10	## distribution.
    11	deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted
    12	deb-src http://archive.ubuntu.com/ubuntu jammy-updates restricted multiverse main universe #Added by software-properties
    13	deb-src http://in.archive.ubuntu.com/ubuntu/ focal-updates main restricted
    14	
    15	## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
    16	## team. Also, please note that software in universe WILL NOT receive any
    17	## review or updates from the Ubuntu security team.
    18	deb http://archive.ubuntu.com/ubuntu jammy universe
    19	deb-src http://in.archive.ubuntu.com/ubuntu/ focal universe
    20	deb http://archive.ubuntu.com/ubuntu jammy-updates universe
    21	deb-src http://in.archive.ubuntu.com/ubuntu/ focal-updates universe
    22	
    23	## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
    24	## team, and may not be under a free licence. Please satisfy yourself as to 
    25	## your rights to use the software. Also, please note that software in 
    26	## multiverse WILL NOT receive any review or updates from the Ubuntu
    27	## security team.
    28	deb http://archive.ubuntu.com/ubuntu jammy multiverse
    29	deb-src http://in.archive.ubuntu.com/ubuntu/ focal multiverse
    30	deb http://archive.ubuntu.com/ubuntu jammy-updates multiverse
    31	deb-src http://in.archive.ubuntu.com/ubuntu/ focal-updates multiverse
    32	
    33	## N.B. software from this repository may not have been tested as
    34	## extensively as that contained in the main release, although it includes
    35	## newer versions of some applications which may provide useful features.
    36	## Also, please note that software in backports WILL NOT receive any review
    37	## or updates from the Ubuntu security team.
    38	deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    39	deb-src http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse #Added by software-properties
    40	deb-src http://in.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
    41	
    42	
    43	deb http://archive.ubuntu.com/ubuntu jammy-security main restricted
    44	deb-src http://archive.ubuntu.com/ubuntu jammy-security restricted multiverse main universe #Added by software-properties
    45	deb-src http://security.ubuntu.com/ubuntu focal-security main restricted
    46	deb http://archive.ubuntu.com/ubuntu jammy-security universe
    47	deb-src http://security.ubuntu.com/ubuntu focal-security universe
    48	deb http://archive.ubuntu.com/ubuntu jammy-security multiverse
    49	deb-src http://security.ubuntu.com/ubuntu focal-security multiverse
    50	
    51	# This system was installed using small removable media
    52	# (e.g. netinst, live or single CD). The matching "deb cdrom"
    53	# entries were disabled at the end of the installation process.
    54	# For information about how to configure apt package sources,
    55	# see the sources.list(5) manual.
    56	# deb https://dl.winehq.org/wine-builds/ubuntu/ focalmain
    57	deb-src https://dl.winehq.org/wine-builds/ubuntu/ focalmain
    58	# deb https://dl.winehq.org/wine-builds/ubuntu/ groovy main # disabled on upgrade to groovy
    59	deb-src https://dl.winehq.org/wine-builds/ubuntu/ focal main
    60	# deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main # disabled on upgrade to groovy
    61	deb-src https://dl.winehq.org/wine-builds/ubuntu/ bionic main
    62

**Comment by shreyansh1827** [comment]
And, i am currently using Ubuntu 22.04

**Comment by yilozt** [comment]
Just need to remove line 51~line 62 of `source.list`. lt seems that you have add wrong repository of Wine.

You can follow [https://wiki.winehq.org/Ubuntu](https://wiki.winehq.org/Ubuntu) to add WineHq to your `source.list`

**Comment by shreyansh1827** [comment]
That worked! Thankyou so much.
