### ISSUE TITLE
Mutter Rounded Gone After updating system

### ISSUE THREAD

**Issue by TimilsinaBimal** [yilozt/mutter-rounded#62]
Hello, I am using ubuntu 22.04 and installed mutter-rounded as instructed. The rounded corners works perfectly. But when I update my system `sudo apt update; sudo apt uprade` The official mutter-common package gets installed and the mutter rounded stops working [since there is no mutter rounded, as it is replaced by mutter-common]. Is this common issue or just in my system? How can I fix it?
OS; Ubuntu 22.04 with NVIDIA GeForce 940MX

**Comment by guruprasadah** [comment]
AFAIK, mutter-rounded completely replaces the original mutter, and doesn't provide any indication that it is different to the original. Hence the OS doesn't know that you have mutter-rounded installed and just downloads the original mutter.

To prevent this from happening, execute the following command in your terminal:
  `sudo apt-mark hold mutter`
This will prevent apt from updating mutter, hence not replacing it. If you want to switch back and want to update mutter again, execute the following command in your terminal:
  `sudo apt-mark unhold mutter`

Hope my answer finds you. Good Luck putting up with Ubuntu and its snaps :laughing:

**Comment by TimilsinaBimal** [comment]
This is what I needed. Thanks for the help!
