### ISSUE TITLE
Scrollbars - how do they look like?

### ISSUE THREAD

**Issue by marcinjahn** [yilozt/mutter-rounded#7]
I wonder how will this patch affect a window like this one:
![image](https://user-images.githubusercontent.com/10273406/142913038-5e346016-5144-43d2-9579-1dbb51eb5571.png)

It is a Microsoft Edge browser. In the bottom-right corner, there is a scrollbar button. Is the patch going to clip it in half?

**Comment by gregor160300** [comment]
![Screenshot from 2021-11-23 11-45-05](https://user-images.githubusercontent.com/7871398/143010551-6517ea08-e168-4f96-bcc2-7dfbbbb1548e.png)
This is edge stable with the path on Fedora 35
