### ISSUE TITLE
Installation error on Manjaro

### ISSUE THREAD

**Issue by fern-end-o** [yilozt/mutter-rounded#88]
Hello! Thanks in advance for any help I can get!
I was using mutter-rounded with Gnome Shell 41, then I upgraded the system (to Gnome Shell 42), which found conflicts between mutter and mutter-rounded, resulting on the replacement of mutter over mutter-rounded. After the upgrade I'm trying to install mutter-rounded again, but the AUR Helper show some errors and fails to install.

This is all the output from the terminal when uninstalling:
https://pastebin.com/e1BNcPL7

This is the testlog.txt:
https://pastebin.com/1w0tRAAL

The workarounds I've tried were:
- Trying to install with "yay -S -dd mutter-rounded"
- Trying to install with "yay -S mutter-rounded"
- Trying to install with "yay -S mutter-rounded" after uninstalling mutter with "pacman -Rsc mutter"
- Trying to install with "yay -S -dd mutter-rounded" after uninstalling mutter with "pacman -Rsc mutter"

Both the tried above resulted the same error and same amount of Fails (16)

**Comment by fern-end-o** [comment]
Fixed by cloning the AUR .git link, then running "makepkg --nocheck -si" from inside the directory created by the cloning procedure.
Apparently the problem was just related to the check() function (hence the "--nocheck" flag on "makepkg").

**Comment by FPSensor** [comment]
fixed
ty
