### ISSUE TITLE
Question: Do I have to rebuild it due to updates?

### ISSUE THREAD

**Issue by joshcangit** [yilozt/mutter-rounded#92]
I like this. I hope the gnome maintainers would patch this into the official Mutter.

Do I have to rebuild this every time this repository updates or also when newer versions of Mutter releases?

**Comment by dawgsome** [comment]
Sadly, yes, at least on Fedora

**Comment by joshcangit** [comment]
Oh I see.
I'm using Ubuntu 22.04 so I can leave it as is right?

**Comment by dawgsome** [comment]
I don't know, I guess you'll see when you upgrade, but I think you'll need to rebuild it (hopefully your hardware is good enough to do that quickly)

**Comment by dawgsome** [comment]
In any case if you use mutter-rounded-settings your settings will be preserved

**Comment by joshcangit** [comment]
The build time was about 5-6 minutes.
I also had to install 209 packages.

Anyway, thank you.
You were right.
There is no newer version yet.
I got to wait and see.
Think I was getting ahead of myself here.
